services:
  - type: web
    name: sasae
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fyp_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
    numInstances: 1