# Generated by Django 3.2.8 on 2021-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, to='core.NormalUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poked_to',
            field=models.ManyToManyField(blank=True, to='core.NGOUser'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='down_vote', to='core.NormalUser'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='report', to='core.NormalUser'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='up_vote', to='core.NormalUser'),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, to='core.NormalUser'),
        ),
    ]
