# Generated by Django 3.2.8 on 2022-06-04 07:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[core.models.validate_contactnumber]),
        ),
        migrations.AlterField(
            model_name='peopleuser',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[core.models.validate_contactnumber]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[core.models.validate_contactnumber]),
        ),
    ]
