# Generated by Django 3.2.8 on 2022-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
