# Generated by Django 3.2.8 on 2022-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngouser',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=123.4342432, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='longitude',
            field=models.DecimalField(blank=43.2343231, decimal_places=16, max_digits=22, null=True),
        ),
    ]
