# Generated by Django 3.2.8 on 2021-12-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_review',
            new_name='review',
        ),
    ]
