# Generated by Django 3.2.8 on 2021-11-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211121_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBT', 'LGBT')], max_length=6),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBT', 'LGBT')], max_length=6),
        ),
    ]
