# Generated by Django 3.2.8 on 2021-12-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_review_report_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngouser',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='peopleuser',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='anonymous',
            new_name='is_anonymous',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='removed',
            new_name='is_removed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_body',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='review',
            new_name='is_reviewed',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='marital_status',
            new_name='is_married',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
