# Generated by Django 3.2.8 on 2022-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220117_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=98.678678, max_digits=22),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=78.0978, max_digits=22),
        ),
    ]
