# Generated by Django 3.2.8 on 2022-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_staff_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='report_review',
            field=models.ManyToManyField(blank=True, related_name='report_reviewed_by', to='core.Report'),
        ),
    ]
