# Generated by Django 3.2.8 on 2021-11-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20211127_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngouser',
            name='pan_cert',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/pan'),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='swc_affl_cert',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/swc'),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peopleuser',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
