# Generated by Django 3.2.8 on 2022-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220407_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
