# Generated by Django 3.2.8 on 2021-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211121_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeuser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
