# Generated by Django 3.2.8 on 2021-11-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211130_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngouser',
            old_name='pan_cert',
            new_name='PAN Certificate',
        ),
        migrations.RenameField(
            model_name='ngouser',
            old_name='swc_affl_cert',
            new_name='Social Welfare Council Affl Certificate',
        ),
    ]
