# Generated by Django 3.2.8 on 2022-01-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220117_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank'),
        ),
    ]
