# Generated by Django 3.2.8 on 2021-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211130_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngouser',
            name='PAN Certificate',
        ),
        migrations.RemoveField(
            model_name='ngouser',
            name='Social Welfare Council Affl Certificate',
        ),
        migrations.AddField(
            model_name='ngouser',
            name='pan_cert',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/pan', verbose_name='PAN Certificate'),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='swc_affl_cert',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/swc', verbose_name='Social Welfare Council Affl Certificate'),
        ),
    ]
