# Generated by Django 3.2.8 on 2021-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211130_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='epay_account',
            field=models.CharField(blank=True, help_text='Khalti as an Electronic Payment Gateway', max_length=20),
        ),
    ]
