# Generated by Django 3.2.8 on 2021-11-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ngouser_epay_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='epay_account',
            field=models.CharField(blank=True, help_text='- Khalti as an Electronic Payment Gateway', max_length=20),
        ),
    ]
