# Generated by Django 3.2.8 on 2021-11-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ngouser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action',
            field=models.CharField(blank=True, choices=[('Post Remove', 'Post Remove'), ('Account Ban', 'Account Ban')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
