# Generated by Django 3.2.8 on 2022-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220315_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='display_picture',
            field=models.ImageField(blank=True, default='default/default_ngo_dp.png', null=True, upload_to='display_picture'),
        ),
    ]
