# Generated by Django 3.2.8 on 2021-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ngouser_epay_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoll',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='poll_reported_by_rn', to='core.PeopleUser'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='req_reported_by_rn', to='core.PeopleUser'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='normal_reported_by_rn', to='core.PeopleUser'),
        ),
    ]
