# Generated by Django 3.2.8 on 2021-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211202_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='poked_on',
            field=models.ManyToManyField(blank=True, related_name='poked_on_rn', to='core.Post'),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='posted_post',
            field=models.ManyToManyField(blank=True, related_name='posted_post_rn', to='core.Post'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='down_vote_rn', to='core.PeopleUser'),
        ),
        migrations.AlterField(
            model_name='postnormal',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='up_vote_rn', to='core.PeopleUser'),
        ),
    ]
