# Generated by Django 3.2.8 on 2022-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220316_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoll',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
