# Generated by Django 3.2.8 on 2021-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211202_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='posted_post',
            field=models.ManyToManyField(blank=True, related_name='ngo_posted_post_rn', to='core.Post'),
        ),
        migrations.AlterField(
            model_name='peopleuser',
            name='posted_post',
            field=models.ManyToManyField(blank=True, related_name='people_posted_post_rn', to='core.Post'),
        ),
    ]
