# Generated by Django 3.2.8 on 2021-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211202_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnormal',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image_rn'),
        ),
    ]
