# Generated by Django 3.2.8 on 2022-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_postpoll_ends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='ends_on',
            field=models.DateTimeField(),
        ),
    ]
