# Generated by Django 3.2.8 on 2022-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_postrequest_ends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoll',
            name='ends_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
