# Generated by Django 3.2.8 on 2021-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_postnormal_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
