# Generated by Django 3.2.8 on 2021-12-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action',
            field=models.CharField(blank=True, choices=[('Post Remove', 'Post Remove'), ('Account Ban', 'Account Ban'), ('Account Delete', 'Account Delete')], max_length=20),
        ),
    ]
